//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeathOfJanuary_Client.DeathOfJanuaryServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DeathOfJanuaryServiceReference.DeathOfJanuaryServiceSoap")]
    public interface DeathOfJanuaryServiceSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        DeathOfJanuary_Client.DeathOfJanuaryServiceReference.HelloWorldResponse HelloWorld(DeathOfJanuary_Client.DeathOfJanuaryServiceReference.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<DeathOfJanuary_Client.DeathOfJanuaryServiceReference.HelloWorldResponse> HelloWorldAsync(DeathOfJanuary_Client.DeathOfJanuaryServiceReference.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name inputVal from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeathOfJanuary", ReplyAction="*")]
        DeathOfJanuary_Client.DeathOfJanuaryServiceReference.DeathOfJanuaryResponse DeathOfJanuary(DeathOfJanuary_Client.DeathOfJanuaryServiceReference.DeathOfJanuaryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeathOfJanuary", ReplyAction="*")]
        System.Threading.Tasks.Task<DeathOfJanuary_Client.DeathOfJanuaryServiceReference.DeathOfJanuaryResponse> DeathOfJanuaryAsync(DeathOfJanuary_Client.DeathOfJanuaryServiceReference.DeathOfJanuaryRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public DeathOfJanuary_Client.DeathOfJanuaryServiceReference.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(DeathOfJanuary_Client.DeathOfJanuaryServiceReference.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public DeathOfJanuary_Client.DeathOfJanuaryServiceReference.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(DeathOfJanuary_Client.DeathOfJanuaryServiceReference.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeathOfJanuaryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeathOfJanuary", Namespace="http://tempuri.org/", Order=0)]
        public DeathOfJanuary_Client.DeathOfJanuaryServiceReference.DeathOfJanuaryRequestBody Body;
        
        public DeathOfJanuaryRequest() {
        }
        
        public DeathOfJanuaryRequest(DeathOfJanuary_Client.DeathOfJanuaryServiceReference.DeathOfJanuaryRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeathOfJanuaryRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string inputVal;
        
        public DeathOfJanuaryRequestBody() {
        }
        
        public DeathOfJanuaryRequestBody(string inputVal) {
            this.inputVal = inputVal;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeathOfJanuaryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeathOfJanuaryResponse", Namespace="http://tempuri.org/", Order=0)]
        public DeathOfJanuary_Client.DeathOfJanuaryServiceReference.DeathOfJanuaryResponseBody Body;
        
        public DeathOfJanuaryResponse() {
        }
        
        public DeathOfJanuaryResponse(DeathOfJanuary_Client.DeathOfJanuaryServiceReference.DeathOfJanuaryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeathOfJanuaryResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DeathOfJanuaryResult;
        
        public DeathOfJanuaryResponseBody() {
        }
        
        public DeathOfJanuaryResponseBody(string DeathOfJanuaryResult) {
            this.DeathOfJanuaryResult = DeathOfJanuaryResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DeathOfJanuaryServiceSoapChannel : DeathOfJanuary_Client.DeathOfJanuaryServiceReference.DeathOfJanuaryServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DeathOfJanuaryServiceSoapClient : System.ServiceModel.ClientBase<DeathOfJanuary_Client.DeathOfJanuaryServiceReference.DeathOfJanuaryServiceSoap>, DeathOfJanuary_Client.DeathOfJanuaryServiceReference.DeathOfJanuaryServiceSoap {
        
        public DeathOfJanuaryServiceSoapClient() {
        }
        
        public DeathOfJanuaryServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DeathOfJanuaryServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DeathOfJanuaryServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DeathOfJanuaryServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DeathOfJanuary_Client.DeathOfJanuaryServiceReference.HelloWorldResponse DeathOfJanuary_Client.DeathOfJanuaryServiceReference.DeathOfJanuaryServiceSoap.HelloWorld(DeathOfJanuary_Client.DeathOfJanuaryServiceReference.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            DeathOfJanuary_Client.DeathOfJanuaryServiceReference.HelloWorldRequest inValue = new DeathOfJanuary_Client.DeathOfJanuaryServiceReference.HelloWorldRequest();
            inValue.Body = new DeathOfJanuary_Client.DeathOfJanuaryServiceReference.HelloWorldRequestBody();
            DeathOfJanuary_Client.DeathOfJanuaryServiceReference.HelloWorldResponse retVal = ((DeathOfJanuary_Client.DeathOfJanuaryServiceReference.DeathOfJanuaryServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DeathOfJanuary_Client.DeathOfJanuaryServiceReference.HelloWorldResponse> DeathOfJanuary_Client.DeathOfJanuaryServiceReference.DeathOfJanuaryServiceSoap.HelloWorldAsync(DeathOfJanuary_Client.DeathOfJanuaryServiceReference.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<DeathOfJanuary_Client.DeathOfJanuaryServiceReference.HelloWorldResponse> HelloWorldAsync() {
            DeathOfJanuary_Client.DeathOfJanuaryServiceReference.HelloWorldRequest inValue = new DeathOfJanuary_Client.DeathOfJanuaryServiceReference.HelloWorldRequest();
            inValue.Body = new DeathOfJanuary_Client.DeathOfJanuaryServiceReference.HelloWorldRequestBody();
            return ((DeathOfJanuary_Client.DeathOfJanuaryServiceReference.DeathOfJanuaryServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DeathOfJanuary_Client.DeathOfJanuaryServiceReference.DeathOfJanuaryResponse DeathOfJanuary_Client.DeathOfJanuaryServiceReference.DeathOfJanuaryServiceSoap.DeathOfJanuary(DeathOfJanuary_Client.DeathOfJanuaryServiceReference.DeathOfJanuaryRequest request) {
            return base.Channel.DeathOfJanuary(request);
        }
        
        public string DeathOfJanuary(string inputVal) {
            DeathOfJanuary_Client.DeathOfJanuaryServiceReference.DeathOfJanuaryRequest inValue = new DeathOfJanuary_Client.DeathOfJanuaryServiceReference.DeathOfJanuaryRequest();
            inValue.Body = new DeathOfJanuary_Client.DeathOfJanuaryServiceReference.DeathOfJanuaryRequestBody();
            inValue.Body.inputVal = inputVal;
            DeathOfJanuary_Client.DeathOfJanuaryServiceReference.DeathOfJanuaryResponse retVal = ((DeathOfJanuary_Client.DeathOfJanuaryServiceReference.DeathOfJanuaryServiceSoap)(this)).DeathOfJanuary(inValue);
            return retVal.Body.DeathOfJanuaryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DeathOfJanuary_Client.DeathOfJanuaryServiceReference.DeathOfJanuaryResponse> DeathOfJanuary_Client.DeathOfJanuaryServiceReference.DeathOfJanuaryServiceSoap.DeathOfJanuaryAsync(DeathOfJanuary_Client.DeathOfJanuaryServiceReference.DeathOfJanuaryRequest request) {
            return base.Channel.DeathOfJanuaryAsync(request);
        }
        
        public System.Threading.Tasks.Task<DeathOfJanuary_Client.DeathOfJanuaryServiceReference.DeathOfJanuaryResponse> DeathOfJanuaryAsync(string inputVal) {
            DeathOfJanuary_Client.DeathOfJanuaryServiceReference.DeathOfJanuaryRequest inValue = new DeathOfJanuary_Client.DeathOfJanuaryServiceReference.DeathOfJanuaryRequest();
            inValue.Body = new DeathOfJanuary_Client.DeathOfJanuaryServiceReference.DeathOfJanuaryRequestBody();
            inValue.Body.inputVal = inputVal;
            return ((DeathOfJanuary_Client.DeathOfJanuaryServiceReference.DeathOfJanuaryServiceSoap)(this)).DeathOfJanuaryAsync(inValue);
        }
    }
}
