//------------------------------------------------------------------------------
// <auto-generated>
//     Denna kod har genererats av ett verktyg.
//     Körtidsversion:4.0.30319.42000
//
//     Ändringar i denna fil kan orsaka fel och kommer att förloras om
//     koden återgenereras.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://EcUtbildning.Hobby", ConfigurationName="IMyHobby")]
public interface IMyHobby
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://EcUtbildning.Hobby/IMyHobby/MyHobby", ReplyAction="http://EcUtbildning.Hobby/IMyHobby/MyHobbyResponse")]
    string MyHobby(string inputVal);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://EcUtbildning.Hobby/IMyHobby/MyHobby", ReplyAction="http://EcUtbildning.Hobby/IMyHobby/MyHobbyResponse")]
    System.Threading.Tasks.Task<string> MyHobbyAsync(string inputVal);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IMyHobbyChannel : IMyHobby, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class MyHobbyClient : System.ServiceModel.ClientBase<IMyHobby>, IMyHobby
{
    
    public MyHobbyClient()
    {
    }
    
    public MyHobbyClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public MyHobbyClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public MyHobbyClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public MyHobbyClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public string MyHobby(string inputVal)
    {
        return base.Channel.MyHobby(inputVal);
    }
    
    public System.Threading.Tasks.Task<string> MyHobbyAsync(string inputVal)
    {
        return base.Channel.MyHobbyAsync(inputVal);
    }
}
