//------------------------------------------------------------------------------
// <auto-generated>
//     Denna kod har genererats av ett verktyg.
//     Körtidsversion:4.0.30319.42000
//
//     Ändringar i denna fil kan orsaka fel och kommer att förloras om
//     koden återgenereras.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://EcUtbildning.DateString", ConfigurationName="IDateAsString")]
public interface IDateAsString
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://EcUtbildning.DateString/IDateAsString/ReturnDateAsString", ReplyAction="http://EcUtbildning.DateString/IDateAsString/ReturnDateAsStringResponse")]
    string ReturnDateAsString(string inputVal);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://EcUtbildning.DateString/IDateAsString/ReturnDateAsString", ReplyAction="http://EcUtbildning.DateString/IDateAsString/ReturnDateAsStringResponse")]
    System.Threading.Tasks.Task<string> ReturnDateAsStringAsync(string inputVal);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IDateAsStringChannel : IDateAsString, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class DateAsStringClient : System.ServiceModel.ClientBase<IDateAsString>, IDateAsString
{
    
    public DateAsStringClient()
    {
    }
    
    public DateAsStringClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public DateAsStringClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public DateAsStringClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public DateAsStringClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public string ReturnDateAsString(string inputVal)
    {
        return base.Channel.ReturnDateAsString(inputVal);
    }
    
    public System.Threading.Tasks.Task<string> ReturnDateAsStringAsync(string inputVal)
    {
        return base.Channel.ReturnDateAsStringAsync(inputVal);
    }
}
