//------------------------------------------------------------------------------
// <auto-generated>
//     Denna kod har genererats av ett verktyg.
//     Körtidsversion:4.0.30319.42000
//
//     Ändringar i denna fil kan orsaka fel och kommer att förloras om
//     koden återgenereras.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://EcUtbildning.ThousandDays", ConfigurationName="ICalculateThousandDays")]
public interface ICalculateThousandDays
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://EcUtbildning.ThousandDays/ICalculateThousandDays/CalculateThousandDays", ReplyAction="http://EcUtbildning.ThousandDays/ICalculateThousandDays/CalculateThousandDaysResp" +
        "onse")]
    string CalculateThousandDays(System.DateTime date);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://EcUtbildning.ThousandDays/ICalculateThousandDays/CalculateThousandDays", ReplyAction="http://EcUtbildning.ThousandDays/ICalculateThousandDays/CalculateThousandDaysResp" +
        "onse")]
    System.Threading.Tasks.Task<string> CalculateThousandDaysAsync(System.DateTime date);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface ICalculateThousandDaysChannel : ICalculateThousandDays, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class CalculateThousandDaysClient : System.ServiceModel.ClientBase<ICalculateThousandDays>, ICalculateThousandDays
{
    
    public CalculateThousandDaysClient()
    {
    }
    
    public CalculateThousandDaysClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public CalculateThousandDaysClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public CalculateThousandDaysClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public CalculateThousandDaysClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public string CalculateThousandDays(System.DateTime date)
    {
        return base.Channel.CalculateThousandDays(date);
    }
    
    public System.Threading.Tasks.Task<string> CalculateThousandDaysAsync(System.DateTime date)
    {
        return base.Channel.CalculateThousandDaysAsync(date);
    }
}
