//------------------------------------------------------------------------------
// <auto-generated>
//     Denna kod har genererats av ett verktyg.
//     Körtidsversion:4.0.30319.42000
//
//     Ändringar i denna fil kan orsaka fel och kommer att förloras om
//     koden återgenereras.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NorthwindService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Shipper", Namespace="http://schemas.datacontract.org/2004/07/NorthwindService")]
    public partial class Shipper : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CompanyNameField;
        
        private string PhoneField;
        
        private int ShipperIdField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompanyName
        {
            get
            {
                return this.CompanyNameField;
            }
            set
            {
                this.CompanyNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone
        {
            get
            {
                return this.PhoneField;
            }
            set
            {
                this.PhoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ShipperId
        {
            get
            {
                return this.ShipperIdField;
            }
            set
            {
                this.ShipperIdField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IShipperService")]
public interface IShipperService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShipperService/GetShipperId", ReplyAction="http://tempuri.org/IShipperService/GetShipperIdResponse")]
    NorthwindService.Shipper GetShipperId(int shipperId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShipperService/GetShipperId", ReplyAction="http://tempuri.org/IShipperService/GetShipperIdResponse")]
    System.Threading.Tasks.Task<NorthwindService.Shipper> GetShipperIdAsync(int shipperId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShipperService/SaveShipper", ReplyAction="http://tempuri.org/IShipperService/SaveShipperResponse")]
    void SaveShipper(NorthwindService.Shipper shipper);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShipperService/SaveShipper", ReplyAction="http://tempuri.org/IShipperService/SaveShipperResponse")]
    System.Threading.Tasks.Task SaveShipperAsync(NorthwindService.Shipper shipper);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IShipperServiceChannel : IShipperService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class ShipperServiceClient : System.ServiceModel.ClientBase<IShipperService>, IShipperService
{
    
    public ShipperServiceClient()
    {
    }
    
    public ShipperServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public ShipperServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ShipperServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ShipperServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public NorthwindService.Shipper GetShipperId(int shipperId)
    {
        return base.Channel.GetShipperId(shipperId);
    }
    
    public System.Threading.Tasks.Task<NorthwindService.Shipper> GetShipperIdAsync(int shipperId)
    {
        return base.Channel.GetShipperIdAsync(shipperId);
    }
    
    public void SaveShipper(NorthwindService.Shipper shipper)
    {
        base.Channel.SaveShipper(shipper);
    }
    
    public System.Threading.Tasks.Task SaveShipperAsync(NorthwindService.Shipper shipper)
    {
        return base.Channel.SaveShipperAsync(shipper);
    }
}
