//------------------------------------------------------------------------------
// <auto-generated>
//     Denna kod har genererats av ett verktyg.
//     Körtidsversion:4.0.30319.42000
//
//     Ändringar i denna fil kan orsaka fel och kommer att förloras om
//     koden återgenereras.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://EcUtbildning.CalculateAge", ConfigurationName="ICalculateAge")]
public interface ICalculateAge
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://EcUtbildning.CalculateAge/ICalculateAge/CalculateAge", ReplyAction="http://EcUtbildning.CalculateAge/ICalculateAge/CalculateAgeResponse")]
    string CalculateAge(System.DateTime birthday);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://EcUtbildning.CalculateAge/ICalculateAge/CalculateAge", ReplyAction="http://EcUtbildning.CalculateAge/ICalculateAge/CalculateAgeResponse")]
    System.Threading.Tasks.Task<string> CalculateAgeAsync(System.DateTime birthday);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface ICalculateAgeChannel : ICalculateAge, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class CalculateAgeClient : System.ServiceModel.ClientBase<ICalculateAge>, ICalculateAge
{
    
    public CalculateAgeClient()
    {
    }
    
    public CalculateAgeClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public CalculateAgeClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public CalculateAgeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public CalculateAgeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public string CalculateAge(System.DateTime birthday)
    {
        return base.Channel.CalculateAge(birthday);
    }
    
    public System.Threading.Tasks.Task<string> CalculateAgeAsync(System.DateTime birthday)
    {
        return base.Channel.CalculateAgeAsync(birthday);
    }
}
