//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Death_Client.DeathServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DeathServiceReference.DeathServicesSoap")]
    public interface DeathServicesSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        Death_Client.DeathServiceReference.HelloWorldResponse HelloWorld(Death_Client.DeathServiceReference.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<Death_Client.DeathServiceReference.HelloWorldResponse> HelloWorldAsync(Death_Client.DeathServiceReference.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name inputVal from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeathCasesJanuary", ReplyAction="*")]
        Death_Client.DeathServiceReference.DeathCasesJanuaryResponse DeathCasesJanuary(Death_Client.DeathServiceReference.DeathCasesJanuaryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeathCasesJanuary", ReplyAction="*")]
        System.Threading.Tasks.Task<Death_Client.DeathServiceReference.DeathCasesJanuaryResponse> DeathCasesJanuaryAsync(Death_Client.DeathServiceReference.DeathCasesJanuaryRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public Death_Client.DeathServiceReference.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(Death_Client.DeathServiceReference.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public Death_Client.DeathServiceReference.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(Death_Client.DeathServiceReference.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeathCasesJanuaryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeathCasesJanuary", Namespace="http://tempuri.org/", Order=0)]
        public Death_Client.DeathServiceReference.DeathCasesJanuaryRequestBody Body;
        
        public DeathCasesJanuaryRequest() {
        }
        
        public DeathCasesJanuaryRequest(Death_Client.DeathServiceReference.DeathCasesJanuaryRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeathCasesJanuaryRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string inputVal;
        
        public DeathCasesJanuaryRequestBody() {
        }
        
        public DeathCasesJanuaryRequestBody(string inputVal) {
            this.inputVal = inputVal;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeathCasesJanuaryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeathCasesJanuaryResponse", Namespace="http://tempuri.org/", Order=0)]
        public Death_Client.DeathServiceReference.DeathCasesJanuaryResponseBody Body;
        
        public DeathCasesJanuaryResponse() {
        }
        
        public DeathCasesJanuaryResponse(Death_Client.DeathServiceReference.DeathCasesJanuaryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeathCasesJanuaryResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DeathCasesJanuaryResult;
        
        public DeathCasesJanuaryResponseBody() {
        }
        
        public DeathCasesJanuaryResponseBody(string DeathCasesJanuaryResult) {
            this.DeathCasesJanuaryResult = DeathCasesJanuaryResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DeathServicesSoapChannel : Death_Client.DeathServiceReference.DeathServicesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DeathServicesSoapClient : System.ServiceModel.ClientBase<Death_Client.DeathServiceReference.DeathServicesSoap>, Death_Client.DeathServiceReference.DeathServicesSoap {
        
        public DeathServicesSoapClient() {
        }
        
        public DeathServicesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DeathServicesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DeathServicesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DeathServicesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Death_Client.DeathServiceReference.HelloWorldResponse Death_Client.DeathServiceReference.DeathServicesSoap.HelloWorld(Death_Client.DeathServiceReference.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            Death_Client.DeathServiceReference.HelloWorldRequest inValue = new Death_Client.DeathServiceReference.HelloWorldRequest();
            inValue.Body = new Death_Client.DeathServiceReference.HelloWorldRequestBody();
            Death_Client.DeathServiceReference.HelloWorldResponse retVal = ((Death_Client.DeathServiceReference.DeathServicesSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Death_Client.DeathServiceReference.HelloWorldResponse> Death_Client.DeathServiceReference.DeathServicesSoap.HelloWorldAsync(Death_Client.DeathServiceReference.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<Death_Client.DeathServiceReference.HelloWorldResponse> HelloWorldAsync() {
            Death_Client.DeathServiceReference.HelloWorldRequest inValue = new Death_Client.DeathServiceReference.HelloWorldRequest();
            inValue.Body = new Death_Client.DeathServiceReference.HelloWorldRequestBody();
            return ((Death_Client.DeathServiceReference.DeathServicesSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Death_Client.DeathServiceReference.DeathCasesJanuaryResponse Death_Client.DeathServiceReference.DeathServicesSoap.DeathCasesJanuary(Death_Client.DeathServiceReference.DeathCasesJanuaryRequest request) {
            return base.Channel.DeathCasesJanuary(request);
        }
        
        public string DeathCasesJanuary(string inputVal) {
            Death_Client.DeathServiceReference.DeathCasesJanuaryRequest inValue = new Death_Client.DeathServiceReference.DeathCasesJanuaryRequest();
            inValue.Body = new Death_Client.DeathServiceReference.DeathCasesJanuaryRequestBody();
            inValue.Body.inputVal = inputVal;
            Death_Client.DeathServiceReference.DeathCasesJanuaryResponse retVal = ((Death_Client.DeathServiceReference.DeathServicesSoap)(this)).DeathCasesJanuary(inValue);
            return retVal.Body.DeathCasesJanuaryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Death_Client.DeathServiceReference.DeathCasesJanuaryResponse> Death_Client.DeathServiceReference.DeathServicesSoap.DeathCasesJanuaryAsync(Death_Client.DeathServiceReference.DeathCasesJanuaryRequest request) {
            return base.Channel.DeathCasesJanuaryAsync(request);
        }
        
        public System.Threading.Tasks.Task<Death_Client.DeathServiceReference.DeathCasesJanuaryResponse> DeathCasesJanuaryAsync(string inputVal) {
            Death_Client.DeathServiceReference.DeathCasesJanuaryRequest inValue = new Death_Client.DeathServiceReference.DeathCasesJanuaryRequest();
            inValue.Body = new Death_Client.DeathServiceReference.DeathCasesJanuaryRequestBody();
            inValue.Body.inputVal = inputVal;
            return ((Death_Client.DeathServiceReference.DeathServicesSoap)(this)).DeathCasesJanuaryAsync(inValue);
        }
    }
}
