//------------------------------------------------------------------------------
// <auto-generated>
//     Denna kod har genererats av ett verktyg.
//     Körtidsversion:4.0.30319.42000
//
//     Ändringar i denna fil kan orsaka fel och kommer att förloras om
//     koden återgenereras.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://EcUtbildning.SocialSecurityNumber", ConfigurationName="IGetSocialSecurityNumber")]
public interface IGetSocialSecurityNumber
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://EcUtbildning.SocialSecurityNumber/IGetSocialSecurityNumber/GetSocialSecuri" +
        "tyNumber", ReplyAction="http://EcUtbildning.SocialSecurityNumber/IGetSocialSecurityNumber/GetSocialSecuri" +
        "tyNumberResponse")]
    string GetSocialSecurityNumber(string inputVal);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://EcUtbildning.SocialSecurityNumber/IGetSocialSecurityNumber/GetSocialSecuri" +
        "tyNumber", ReplyAction="http://EcUtbildning.SocialSecurityNumber/IGetSocialSecurityNumber/GetSocialSecuri" +
        "tyNumberResponse")]
    System.Threading.Tasks.Task<string> GetSocialSecurityNumberAsync(string inputVal);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IGetSocialSecurityNumberChannel : IGetSocialSecurityNumber, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class GetSocialSecurityNumberClient : System.ServiceModel.ClientBase<IGetSocialSecurityNumber>, IGetSocialSecurityNumber
{
    
    public GetSocialSecurityNumberClient()
    {
    }
    
    public GetSocialSecurityNumberClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public GetSocialSecurityNumberClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public GetSocialSecurityNumberClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public GetSocialSecurityNumberClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public string GetSocialSecurityNumber(string inputVal)
    {
        return base.Channel.GetSocialSecurityNumber(inputVal);
    }
    
    public System.Threading.Tasks.Task<string> GetSocialSecurityNumberAsync(string inputVal)
    {
        return base.Channel.GetSocialSecurityNumberAsync(inputVal);
    }
}
